// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4T14lfpVld8a63PfBAGgdokhYLXCX9pU',
    appId: '1:45496130874:web:de45d79b98d4fa10608403',
    messagingSenderId: '45496130874',
    projectId: 'fir-flutter-codelab-e0c2a',
    authDomain: 'fir-flutter-codelab-e0c2a.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e0c2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRo0sWXLsOI5Wh6P3r5SxJcMYmvBW-fiU',
    appId: '1:45496130874:android:95e535fa4898e1ca608403',
    messagingSenderId: '45496130874',
    projectId: 'fir-flutter-codelab-e0c2a',
    storageBucket: 'fir-flutter-codelab-e0c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1eEXlKIstgMDXMbJU6yCW3R1o1FZIs4',
    appId: '1:45496130874:ios:5e0cc1798ff14c0b608403',
    messagingSenderId: '45496130874',
    projectId: 'fir-flutter-codelab-e0c2a',
    storageBucket: 'fir-flutter-codelab-e0c2a.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1eEXlKIstgMDXMbJU6yCW3R1o1FZIs4',
    appId: '1:45496130874:ios:62be5e2920be6b8c608403',
    messagingSenderId: '45496130874',
    projectId: 'fir-flutter-codelab-e0c2a',
    storageBucket: 'fir-flutter-codelab-e0c2a.appspot.com',
    iosBundleId: 'com.example.signin.RunnerTests',
  );
}
